'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import styles from './InfoGraphic.module.css';

export type InfoGraphicHighlight = {
  title: string;
  note: string;
};

type InfoGraphicProps = {
  id: string;
  /** Asset base name inside /public/images (generated by _build-img.js). */
  name: string;
  width: number;
  height: number;
  alt: string;
  heading: string;
  caption: string;
  highlights: InfoGraphicHighlight[];
};

/** Sources that need a media query, widest first. */
const WIDE_SOURCES = [
  { media: '(min-width: 1300px)', size: 1672 },
  { media: '(min-width: 900px)', size: 1300 },
  { media: '(min-width: 560px)', size: 900 },
];

/** Smallest crop, also the <img> fallback for every narrower viewport. */
const SMALL_SOURCE = 520;

const FULL_SIZE = 1672;

export function InfoGraphic({
  id,
  name,
  width,
  height,
  alt,
  heading,
  caption,
  highlights,
}: InfoGraphicProps) {
  const [open, setOpen] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const closeRef = useRef<HTMLButtonElement>(null);
  const base = `/images/${name}`;

  const close = useCallback(() => {
    setOpen(false);
    triggerRef.current?.focus();
  }, []);

  useEffect(() => {
    if (!open) return;

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    closeRef.current?.focus();

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close();
    };
    window.addEventListener('keydown', onKeyDown);

    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener('keydown', onKeyDown);
    };
  }, [open, close]);

  return (
    <section id={id} className={styles.root} aria-labelledby={`${id}-heading`}>
      <div className="wrap">
        <h2 id={`${id}-heading`} className={styles.srOnly}>
          {heading}
        </h2>

        <figure className={styles.frame}>
          <button
            ref={triggerRef}
            type="button"
            className={styles.zoom}
            onClick={() => setOpen(true)}
            aria-label={`Enlarge diagram: ${heading}`}
          >
            <picture>
              {WIDE_SOURCES.map((source) => (
                <source
                  key={`webp-${source.size}`}
                  type="image/webp"
                  media={source.media}
                  srcSet={`${base}-${source.size}.webp`}
                />
              ))}
              <source type="image/webp" srcSet={`${base}-${SMALL_SOURCE}.webp`} />
              {WIDE_SOURCES.map((source) => (
                <source
                  key={`png-${source.size}`}
                  media={source.media}
                  srcSet={`${base}-${source.size}.png`}
                />
              ))}
              <img
                className={styles.art}
                src={`${base}-${SMALL_SOURCE}.png`}
                alt={alt}
                width={width}
                height={height}
                loading="lazy"
                decoding="async"
              />
            </picture>
            <span className={styles.hint}>Tap to enlarge</span>
          </button>

          <figcaption className={styles.caption}>{caption}</figcaption>
        </figure>

        <ul className={styles.highlights}>
          {highlights.map((item) => (
            <li key={item.title} className={styles.highlight}>
              <span className={styles.highlightTitle}>{item.title}</span>
              <span className={styles.highlightNote}>{item.note}</span>
            </li>
          ))}
        </ul>
      </div>

      {open && (
        <div className={styles.overlay} role="dialog" aria-modal="true" aria-label={heading}>
          <div className={styles.backdrop} onClick={close} aria-hidden="true" />
          <div className={styles.bar}>
            <span>{heading}</span>
            <button
              ref={closeRef}
              type="button"
              className={styles.close}
              onClick={close}
              aria-label="Close enlarged diagram"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <path stroke="currentColor" strokeWidth="2" strokeLinecap="round" d="M6 6l12 12M18 6L6 18" />
              </svg>
            </button>
          </div>
          <div className={styles.pan}>
            <img
              className={styles.zoomArt}
              style={{ width: `${width}px` }}
              src={`${base}-${FULL_SIZE}.png`}
              alt={alt}
              width={width}
              height={height}
            />
          </div>
        </div>
      )}
    </section>
  );
}

const CAPABILITY_HIGHLIGHTS: InfoGraphicHighlight[] = [
  { title: 'One private Internet identity', note: 'Your XID. Not rented — yours to keep, move, and recover.' },
  { title: 'Communication', note: 'Text, call, meet, files, and verify from the same identity.' },
  { title: 'Reach policy', note: 'You decide who can contact you. Approve, verify, or decline.' },
  { title: 'Trusted devices', note: 'Phone, laptop, desktop, and whatever device comes next.' },
  { title: 'Any network', note: 'Wi-Fi, fiber, mobile, satellite — the transport is a detail.' },
  { title: 'Private relationships', note: 'Pairwise by design. No one sees your other connections.' },
  { title: 'Appointments', note: 'Share available slots only. Keep the rest of your calendar private.' },
  { title: 'Verified organizations', note: 'Connect through verifiable capabilities, not personal data.' },
];

export function CapabilityMap() {
  return (
    <InfoGraphic
      id="capabilities"
      name="one-identity-many-capabilities"
      width={1672}
      height={941}
      heading="One identity. Many capabilities."
      alt="Diagram titled One identity, many capabilities. XDomain sits at the centre as one private Internet identity — your XID — with eight capabilities radiating from it: one private Internet identity, communication, reach policy, trusted devices, any network, private relationships, appointments, and verified organizations."
      caption="How to read this: the centre is your XID. Each spoke is a capability that runs on that one identity — not a separate app, account, or provider."
      highlights={CAPABILITY_HIGHLIGHTS}
    />
  );
}

const WHY_HIGHLIGHTS: InfoGraphicHighlight[] = [
  { title: 'One identity instead of many', note: 'No more juggling phone numbers, emails, or app logins.' },
  { title: 'No dependency on phone or email', note: 'You control your identity, not a provider.' },
  { title: 'Less spam and impersonation', note: 'Harder to fake, easier to trust.' },
  { title: 'Works across any network', note: 'One identity on your phone, computer, watch, or future devices.' },
  { title: 'Easier appointments and direct communication', note: 'Reach the right person without sharing your calendar.' },
  { title: 'Reduced roaming and platform lock-in', note: 'Take your identity with you — anywhere.' },
  {
    title: 'A foundational identity layer',
    note: 'A neutral, open layer across all networks and platforms — a new category with global reach.',
  },
  {
    title: 'Platform for real-world utility',
    note: 'Communication, scheduling, and verification built on a single identity.',
  },
];

export function WhyXDomainMatters() {
  return (
    <InfoGraphic
      id="why-xdomain"
      name="why-xdomain-matters"
      width={1672}
      height={857}
      heading="Why XDomain matters."
      alt="Infographic titled Why XDomain matters. Today identity is fragmented across providers — multiple addresses, provider-owned, no control. With XDomain there is one identity everywhere, under your rules. It then lists what changes for users and why it is a foundational layer for investors."
      caption="The full picture: what changes for people day to day, and why a neutral identity layer is a foundation others can build on."
      highlights={WHY_HIGHLIGHTS}
    />
  );
}